name: Schemas Script
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 12.x

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy 🚀
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ./
          branch: main
